### PR TITLE
Add Japanese locale

### PR DESCRIPTION
**Pull request by shelaf**

### CODE REVIEW

**Comment by mexmer** [comment]
you can create locales as separate mod, and upload it to modportal. so in future, when i change something, you can update it yourself.
if you don't know how, i might put sample localization mod on repo.

localization mod consist only from localization file, and info file, other resource files are not required

somelocalizationmod_0.0.1/locale/[LC]/sciencecosttweaker.cfg
somelocalizationmod_0.0.1/info.json

where [LC] is replaced by locale code 
info.json content is
```
{
  "name": "somelocalizationmod",
  "version": "version",
  "factorio_version":"0.16",
  "title": "Some mod localization",
  "author": "yourname",
  "dependencies": ["base >= 0.16.0", "ScienceCostWeakerM" ], 
  "contact": "",
  "homepage": "
  "description": "localization of mod"
}
```

**Comment by shelaf** [comment]
Yes, I know.
You mean you are not going to include other locale? If so, I will close this PR.

**Comment by mexmer** [comment]
i can add them for next release, but currently i'm busy with RL, so i'm not sure, if release will be this or next week. that''s why i suggested separate mod. there will be no new stuff in new version, just some fixes and tweaks.

**Comment by shelaf** [comment]
No problem. Thanks.

**Pull request merged**
