### PR TITLE
Fix softlock at blue science (Issue #79)

### PR DESCRIPTION
**Pull request by sweetcornwhiskey**
Flash fuel is uncraftable because of a softlock at chemical science. This would add the craftable flash fuel recipe to fix the softlock.

### CODE REVIEW

**Comment by mexmer** [comment]
is this patch for vanilla version of game?

**Comment by sweetcornwhiskey** [comment]
Yes this is for vanilla

**Comment by sweetcornwhiskey** [comment]
I did also find a fix for the Bob's power update (Issue #77) by the way if you'd like me to add that. I do see that it was already assigned to someone else though.

**Comment by mexmer** [comment]
@KiwiHawk is working on #77 he needs to fix that for seablock integration, but if you have PR for that, submit it, i will check it later. at least he will have more time for seablock.

**Pull request closed without merging**
