### PR TITLE
Recent Angel Patch Breaks Science Pack Adjustment

### PR DESCRIPTION
**Pull request by Polar-Zero**
Along with #47, Latest Angel Patch ALSO Breaks some of mods Functionality.
To Fix This, Just Add Name/Amount Check to Science Pack Adjustment.
With #47 & This, mod seems work Fine at 0.18.28 :)

### CODE REVIEW

**Comment by evandy0** [comment]
I believe this is a duplicate of #44 implemented by KingArthur...  (different change, same problem).    I am running the newest SCT with KingArthur's fix and do not need this PR at any rate.

**Comment by mexmer** [comment]
i have no idea what is good for that change in final fixes, those should be not affected by angel change, so fix should not be needed, while science connection was broken, so i uses #44 from KingArthur for that.

**Comment by Polar-Zero** [comment]
This Patch is for EXTENDED Setting with Angels mod :D
For Normal & NoAdjustment, This patch NOT Required

**Comment by mexmer** [comment]
ok, thanks for info, i will check it later. tbh. i don't play on other settings than normal. those settings are preserved from original uberwaffe mod, and they probly need to be rescaled ....

**Pull request closed without merging**
